import java.util.Arrays;

public class RandomNumber {
    public int[] generatingRandomValues(int size){ 
        int[] randomDigit = new int[size]; // array of the given size.
        for(int i = 0; i < size; i++){
            randomDigit[i] = (int)(Math.random() * 9000) + 1000; // generating 4 digit random number between 1000 and 9999
        } 
        return randomDigit;
    }

    public double[] findAverageMinMax(int[] numbers){
        double[] result = new double[3];
        int min_Value = numbers[0];
        int max_Value = numbers[1];
        int sum = 0;  

        for(int i = 0; i < numbers.length; i++){
            sum += numbers[i];
            min_Value = Math.min(min_Value, numbers[i]); // finding the minimum value
            max_Value = Math.max(max_Value, numbers[i]); // finding the maximum value
        } 

        double average = (double)sum / numbers.length; // finding the average
        result[0] = min_Value; 
        result[1] = max_Value; 
        result[2] = average;

        return result;
    }

    public static void main(String[] args) {
        RandomNumber obj = new RandomNumber(); 
        int[] randomDigitResult = obj.generatingRandomValues(5); // calling the method to generate random numbers
        System.out.println("Random digit generated by array value is " + (Arrays.toString(randomDigitResult))); // printing random number array.

        double[] ans = obj.findAverageMinMax(randomDigitResult); // calling the method to find average and min max

        System.out.println("The minimum value of the number is " + ans[0]); 
        System.out.println("The maximum value of the number is " + ans[1]); 
        System.out.println("The average value of the number is " + ans[2]);       
    }
}
